const DICT = {
  parts: [
    "fluk",
    "ber",
    "ploc",
    "zap",
    "fro",
    "blo",
    "klu",
    "ist",
    "ber",
    "yo",
    "zat",
    "up",
    "schr",
    "ulli",
    "oloa",
    "ool",
    "tal",
    "ziz",
    "zop",
    "glop",
    "ilo",
    "yak",
    "wus",
    "won",
    "obi",
    "jae",
    "kloa",
    "aba",
    "saka",
    "lopo",
    "ales",
    "per",
    "dis",
    "ence",
    "ness",
    "pres",
    "main",
    "flo",
    "wag",
    "zyo",
    "imo"
  ],
  appearence: [
    "adorable",
    "fair",
    "old-fashioned",
    "alluring",
    "fancy",
    "perfect",
    "attractive",
    "filthy",
    "plain",
    "barbarous",
    "fine",
    "pleasant",
    "beautiful",
    "glamorous",
    "precious",
    "bloody",
    "glowing",
    "quaint",
    "blushing",
    "gorgeous",
    "scruffy",
    "boorish",
    "graceful",
    "self-assured",
    "bright",
    "grotesque",
    "shiny",
    "clean",
    "handsome",
    "slender",
    "clumsy",
    "healthy",
    "snobbish",
    "colorful",
    "hilarious",
    "sparkling",
    "homely",
    "splendid",
    "cultured",
    "hurt",
    "spotless",
    "disheveled",
    "tense",
    "drab",
    "lovely",
    "dull",
    "magnificent",
    "vivacious",
    "elegant",
    "misty",
    "warm",
    "erratic",
    "muddy",
    "wild",
    "ugly",
    "disgusting"
  ],
  personnality: [
    "aggressive",
    "agreeable",
    "ambitious",
    "brave",
    "calm",
    "delightful",
    "eager",
    "faithful",
    "gentle",
    "happy",
    "jolly",
    "kind",
    "lively",
    "nice",
    "obedient",
    "polite",
    "proud",
    "silly",
    "thankful",
    "victorious",
    "witty",
    "wonderful",
    "zealous",
    "angry",
    "bewildered",
    "clumsy",
    "defeated",
    "embarrassed",
    "fierce",
    "unfriendly",
    "grumpy",
    "helpless",
    "itchy",
    "jealous",
    "lazy",
    "timid",
    "tasty",
    "stupid",
    "drunk",
    "unpleasant",
    "mysterious",
    "nervous",
    "obnoxious",
    "panicky",
    "pitiful",
    "repulsive",
    "scary",
    "thoughtless",
    "uptight",
    "worried"
  ],
  races: [
    "aliens",
    "monsters",
    "humans",
    "elves",
    "dwarfs",
    "creatures",
    "robots",
    "gods",
    "giants",
    "ants",
    "dolphins",
    "warriors",
    "ghosts",
    "smugglers",
    "pirates",
    "deamons",
    "celebrities",
    "artists"
  ],
  finish: [".", ":)", ":o", "!", ";)", "<3"]
};

const makeName = (dict = DICT.parts) => {
  let name = [random(dict)];
  name.push(random(dict));
  while (Math.random() < 0.5) {
    name.push(random(dict));
  }
  return capitalize(name.join(""));
};

function isVowel(c) {
  return ["a", "e", "i", "o", "u", "h"].indexOf(c.toLowerCase()) !== -1;
}

const makeSentence = (dict = DICT) => {
  const planetAdj = random(dict.appearence);
  const article = isVowel(planetAdj[0]) ? "an" : "a";
  return [
    makeName(dict.parts),
    "is",
    article,
    planetAdj,
    "planet inhabited by",
    random(dict.personnality),
    random(dict.races),
    random(dict.finish)
  ].join(" ");
};
